### ISSUE TITLE
Summary - Exceeds Expectation

### ISSUE THREAD

**Issue by davecastlevania** [SaxonScarlet/prj-rev-bwfs-dasmoto#4]
Great job with this project! I have no complaints about how you put this together. It looks like you went above and beyond what the expectations were for the project. I like how you started using DIVs, comments, and keeping your code clean. Great job! Keep up these habits, they will go far in your career as a developer.

**Comment by SaxonScarlet** [comment]
Thank you for the feedback (Especially on ampersand note).
